
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.13
      - name: install deps
        run: bun i

      - name: build
        run: bun run build
      - name: lint
        run: bun run lint
      - name: test
        run: bun test