name: Deploy with Blumen
on:
  push:
    branches: main
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      cid: ${{ steps.pack_blumen.outputs.cid }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.13
      - name: Install Blumen
        run: bun i -g blumen@0.16.1
      - name: Build website
        run: cd site && bun i && bun run build
      - name: Deploy
        run: cd site && blumen deploy .vitepress/dist --dnslink blumen.stauro.dev
        env:
          BLUMEN_CF_KEY: ${{ secrets.BLUMEN_CF_KEY }}
          BLUMEN_CF_ZONE_ID: ${{ secrets.BLUMEN_CF_ZONE_ID }}
          BLUMEN_PINATA_TOKEN: ${{ secrets.BLUMEN_PINATA_TOKEN }}
          BLUMEN_STORACHA_PROOF: ${{ secrets.BLUMEN_STORACHA_PROOF }}
          BLUMEN_STORACHA_TOKEN: ${{ secrets.BLUMEN_STORACHA_TOKEN }}
          BLUMEN_LIGHTHOUSE_TOKEN: ${{ secrets.BLUMEN_LIGHTHOUSE_TOKEN }}
          BLUMEN_4EVERLAND_TOKEN: ${{ secrets.BLUMEN_4EVERLAND_TOKEN }}